name: DevSecOps Pipeline for Flask Application (Gunicorn) 

on: [push]

jobs:
  build:
    runs-on: Ubuntu-latest
    steps:
    - name: Setup Python            
      uses: actions/setup-python@v5.4.0
      with:
        python-version: '3.10'

    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: install requirements
      run: |
        pip install -r requirements.txt
        pip install flake8 bandit safety
  
    - name: code linting
      run: flake8 app.py

    # Bandit scans Python code for common security issues like insecure use of eval().
    # - name: Bandit Scan
    #   run: bandit -r .

    # using Safety - for checking the vulnerabilites in the packages
    - name: safety package auditing
      run: safety check --file=requirements.txt --json > safety-report.json  

    - name: Gitleaks
      uses: gitleaks/gitleaks-action@v2.3.4


    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: sailalithdevops
        password: ${{ secrets.DOCKER_PASSWORD }}


    - name: Docker push
      run: |
        docker build -t sailalithv/flask-devsecops-app:${{ github.run_id }} .
        docker push sailalithv/flask-devsecops-app:${{ github.run_id }}
