name: DevSecOps Pipeline for Flask Application (Gunicorn) 

on: [push]

jobs:
  build:
    runs-on: Ubuntu-latest
    steps:
    - name: Setup Python            
      uses: actions/setup-python@v5.4.0
      with:
        python-version: '3.10'

    - name: install requirements
      run: |
        pip install -r requirements.txt
        pip install flake8 bandit safety

    - name: code linting
      run: |
        flake8 app.py
